### PR TITLE
Upgraded OTEL libraries and examples

### PR DESCRIPTION
**Pull request by Ahbrown41**
- [X] Do only one thing
- [X] Non breaking API changes
- [X] Tested

### What did this pull request do?

- Upgraded all libraries
- Upgrade examples to Go 1.20
- Fixed OTEL issues with newest OTEL libraries
- Executed examples

### User Case Description

- Allowing it to work with other OTEL changes

### CODE REVIEW

**Comment by zstone12** [comment]
@Ahbrown41 Thanks fou you Code.Can you help to fix the CI?

**Comment by Ahbrown41** [comment]
> @Ahbrown41 Thanks fou you Code.Can you help to fix the CI?

So I am not as used to Github Actions but when I run these commands it works fine but in Github Actions appears to fail:

```
go vet -stdmethods=false $(go list ./...)
  go vet -stdmethods=false $(go list ./...)
  go install mvdan.cc/gofumpt@v0.5.0
  test -z "$(gofumpt -l -extra .)"
```

Have you seen this before or do you see an actual error that I have not been able to see so far?

**Comment by zstone12** [comment]
> > @Ahbrown41 Thanks fou you Code.Can you help to fix the CI?
> 
> So I am not as used to Github Actions but when I run these commands it works fine but in Github Actions appears to fail:
> 
> ```
> go vet -stdmethods=false $(go list ./...)
>   go vet -stdmethods=false $(go list ./...)
>   go install mvdan.cc/gofumpt@v0.5.0
>   test -z "$(gofumpt -l -extra .)"
> ```
> 
> Have you seen this before or do you see an actual error that I have not been able to see so far?

I will check it later.

**Comment by zstone12** [comment]
@Ahbrown41 It was just a simple formatting issue, so I went ahead and fixed it directly on your branch. Thanks for your PR:D.

**Comment by DavidS-om** [comment]
Can we please get a release of this? Without users of this are stranded on outdated otel versions.

**Comment by DavidS-om** [comment]
Brilliant, thank you!! :heart_decoration:

**Pull request merged**
